apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-deployment
  labels:
    app: healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: capstone-app-container
        image:  preethiadmin/healthcare:1.0
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
spec:
  type: LoadBalancer
  selector:
    app: healthcare-app
  ports:
  - port: 80
    
